version: "3"

networks:
  default:
    external:
      name: dinamic_net

services:
  dinamic_nginx:
    container_name: dinamic_nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "5020:80"
      - "80:80"
    volumes:
      - type: bind
        source: ../../../fherman/back/html
        target: /usr/share/nginx/html/fherman/html
        bind:
          propagation: shared
      - ./nginx/logs:/var/log/nginx/
      - ../../impulse_v2/back:/usr/share/nginx/html/impulse_v2:cached
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:cached
      - ./nginx/sites-enabled:/etc/nginx/sites-available:cached