version: "3"

networks:
  default:
    external:
      name: dinamic_net

services:
  dinamic-httpd:
    container_name: dinamic-httpd
    build:
      context: ./httpd/
      dockerfile: Dockerfile
    ports:
      - "8003:8002"
      - "8002:8002"
      - "80:80"
    volumes:
      - ../../aitek_wp:/usr/local/apache2/htdocs/aitek_wp:cached
      - ../../wonder_wp:/usr/local/apache2/htdocs/wonder_wp:cached
      - ./httpd/logs:/usr/local/apache2/logs/:delegated
      #- ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/sites-enabled:/usr/local/apache2/sites-enabled:cached
      - ./httpd/sites-enabled:/usr/local/apache2/sites-available:cached
